### ISSUE TITLE
Contributing Guideline

### ISSUE THREAD

**Issue by WiLuX-Source** [ShadowTheHedgehogHacking/ShdTH-Reloaded#10]
Hello, I found about this project yesterday. I tried it and my experience with it so far is awesome. I think you guys should have a roadmap or contributing guideline so people like me can assist with your progress thank you for hard work.

**Comment by dreamsyntax** [comment]
Honestly, the project is pretty much wrapped up for the most part as we are working on other projects. We did have a Trello board to manage during the course of it.

Some things that come to mind (if you have gecko / asm experience). Most of these are pretty advanced but posting them anyway:
- Last Story / Expert Mode credits skip
- Light dash bug https://youtu.be/9N835-0PNQU (this is an original game issue, but we were not able to fix in Reloaded)
- .fog file RGBA GameCube float error
- Space Gadget (Gravity) physics transition errors (original game issue)
- Make red rings save in Expert or modify the ghost red rings code to always be ghost in expert
- add remappable action support for light dash (and possibly other actions)
- allow sliding on a slope (shadow physics for ground has some weird restrictions in original)
- memory constraint optimizations / work arounds

If you have 3DSMax / Blender experience:
- Make all events fully 16:9 compatible for widescreen editions; Ex: zoom/stretching the 4:3 stills in Sky Troops intro cutscene

Misc:
- add mobile build instructions for those on Android (its possible with for example the xperia64 rom patcher for those with phones only)
- Fluent Japanese translator and are able to help translate the game. A program would be built for one-time per line entry and will automatically apply to the entire game's reuse of specific lines, to reduce churn/repeated translations.


Otherwise if you are more interested in the level design side, I would recommend making your own Shadow project (Reloaded is Creative Commons so anyone is free to base their work off Reloaded as a base if they wish).


If any of these items interest you can chat with me on Discord or Matrix

**Comment by WiLuX-Source** [comment]
Hello, thank you for telling the current problems and categorizing the needed steps for the project.

As for the gecko / asm experience I dont have that much knowledge with that kind of stuff. So I'll just skip this part.

About the making all events fully 16:9 compatible for widescreen you mean **I BET NO ONE EXPECTED THIS BABY COULD FLY** sequence or **THIS BLUE SKY...** sequence?

As for the misc stuff I'll look into how xperia64 rom patcher works and how someone can patch the game with it. This looks relatively easier compared to the other tasks. As for Japenese I don't know it. But DeepL have some really great translation quality so check it out if you want.

**Comment by dreamsyntax** [comment]
Yes, for the events there are a number like prison island that flash PNG in 4:3 and because of this you can see the background when you otherwise should not. Even last story has a few like this iirc.

Just to be clear there are probably better rom patchers, I use VCDiff algorithm in a mode compatible with xdelta3 to generate my patches, so it doesn't have to be the xperia64 one. Just a patcher that is (ideally) open source and works with that type of patch. I just heard from someone in comments that they successfully applied v1.0 using the xperia64 one, but have not yet verified myself.

DeepL is not sufficient in my experience to have coherent translation. Maybe with better models coming out this may change in the future, but at this time I did not find it worth me personally making integration with it. Not to stop anyone from making one though, its certainly better than not having a translation. I just don't want to consider it officially as part of Reloaded is all.

**Comment by WiLuX-Source** [comment]
> Yes, for the events there are a number like prison island that flash PNG in 4:3 and because of this you can see the background when you otherwise should not. Even last story has a few like this iirc.

Okay I'll try a few things about this. If I get a promising result I'll tell you.

> Just to be clear there are probably better rom patchers, I use VCDiff algorithm in a mode compatible with xdelta3 to generate my patches, so it doesn't have to be the xperia64 one. Just a patcher that is (ideally) open source and works with that type of patch. I just heard from someone in comments that they successfully applied v1.0 using the xperia64 one, but have not yet verified myself.

So any rom patcher is fine but preferably open-source okay. If I get a promising result I'll tell you.

> DeepL is not sufficient in my experience to have coherent translation. 

I see. Hope you can find one.

**Comment by dreamsyntax** [comment]
Just an update, I tested and found
https://github.com/btimofeev/UniPatcher

Works with my patches, so if you decide to look into it please reference this rather than xperia64

**Comment by WiLuX-Source** [comment]
Yeah, I am making progress. Let me check out.

**Comment by WiLuX-Source** [comment]
> Just an update, I tested and found https://github.com/btimofeev/UniPatcher
> 
> Works with my patches, so if you decide to look into it please reference this rather than xperia64

Thank you for telling me this indeed relatively easier than xperia rom patcher just got it up and working.

**Comment by WiLuX-Source** [comment]
Hello, I opened the PR please review it and would like to discuss some things on the discord `Wilux#3091`. I'm closing this issue since you already answered my question.
