### ISSUE TITLE
[REQUEST] Xbox port of this mod

### ISSUE THREAD

**Issue by Hydra-Spectre** [ShadowTheHedgehogHacking/ShdTH-Reloaded#13]
So, this mod to fix Shadow the Hedgehog was made for the GameCube.
However, the Xbox version is the definitive version of the game, with slightly better graphics, more consistent performance, and better quality FMVs and audio (especially as the Xbox supports discrete Dolby Digital 5.1ch output).

It would be great if this mod could be ported to the Xbox version of the game, for the few people who could run Xbox emulators, or have a modded Xbox.

**Comment by dreamsyntax** [comment]
This is something I will never do.

As for performance:
- Nintendont (running game in Wii clockspeed) runs better than Xbox
- Dolphin with OC CPU setting of at least 136% results in stable 60fps beating Xbox


Why no Xbox/PS2 port:
- There is not yet good debugging tools for Xbox modding (xbox emulation was also not a thing for shadow until recent years)
- PS2 shadow is the worst performing version
- Functions not identical between Xbox and GC build. It would largely require doing this mod from scratch.

Graphics/FMV can be replaced with dolphin tex replacement or swapping the files (may need reenc, but its so marginal not worth it).
Audio unfortunately can not be ported from Xbox, at least not without lots of effort.


Our code is open and anyone is free to do such a port if they wish but it would be lots of effort.

I would be more interested in a proper shadow decomp rather than spend effort in this port.
