### ISSUE TITLE
Random crashes, especially in cyber levels

### ISSUE THREAD

**Issue by NithyanthK** [ShadowTheHedgehogHacking/ShdTH-Reloaded#14]
Random crashes, especially in cyber levels
I get crashes that freeze the game, sometimes closing dolhpin.
Im using the graphics addons at 1440p with vertex rounding off.
specs r5 3600 rtx 3060 ti
any help?

**Comment by dreamsyntax** [comment]
Post your GUPE8P.ini


What version of Dolphin
Do you have Dual Core ON
Which Graphics Backend are you using

**Comment by NithyanthK** [comment]
I have dual core on 
version of dolphin is 5.0 19870
I'm using openGL but I can try dx11
[GUPE8P - Copy.txt](https://github.com/ShadowTheHedgehogHacking/ShdTH-Reloaded/files/13431773/GUPE8P.-.Copy.txt)
I renamed it to upload to github

**Comment by dreamsyntax** [comment]
This game runs best with DX11 or Vulkan, so either is preferred.
The GUPE8P config looks fine.

Does an exception get thrown or does it just die? Is it consistent? 

In general Dual Core can cause random crashes with Dolphin, so my initial suspicion is just bad luck with Dual Core.
If your system can handle it with it off, give that a go. A Ryzen 5 should be able to no problem.

Otherwise, this game in general (mods or not) has crashing sometimes anyway. But it shouldn't be occurring all the time.

If you see a popup 
like this:

![invalidwrite-2](https://github.com/ShadowTheHedgehogHacking/ShdTH-Reloaded/assets/14857235/51966806-c615-4cd4-9c88-c0581c819c94)

Then please let me know what it says when it crashes.

**Comment by NithyanthK** [comment]
I got an error just now with dx11 saying FIFO is too fast or something along those lines. Forze my display with the audio still running. Ill turn off dual core

**Comment by dreamsyntax** [comment]
> I got an error just now with dx11 saying FIFO is too fast or something along those lines. Forze my display with the audio still running. Ill turn off dual core

Ah yeah, anything FIFO related is dual core.

**Comment by dreamsyntax** [comment]
I'm assuming this is resolved. Closing in a few days.

**Comment by NithyanthK** [comment]
I receive slowdown when I lose rings, anyway to fix that?

**Comment by dreamsyntax** [comment]
The game is CPU constrained. On real hardware it sometimes dips into 40fps.

Besides following Dolphin optimization guide for this game (basically use all hacks in Graphics) you can tweak the Config > Advanced > CPU Clock Override value to boost the emulated GameCube's CPU clock.

The higher the value the better it will run, but it depends on your own real CPU if it can keep up.
I recommend at least 132%, maybe try 165% for Reloaded in most cases, but experiment.

*NOTE each game reset it will automically default to 150%. You can change this by removing the overclock 1.5 line in the GUPE8P.ini

In this video skip to the optimization section
https://youtu.be/uv9gpqEbXU4 2:20
