### ISSUE TITLE
batch file failing even with correct iso

### ISSUE THREAD

**Issue by explosionenjoyer** [ShadowTheHedgehogHacking/ShdTH-Reloaded#15]
"A subdirectory or file old already exists. xdelta3: secondary compression: lzma xdelta3: file open failed: read: GUPE8P.iso: The system cannot find the file specified. The system cannot find the file specified."

**Comment by dreamsyntax** [comment]
Delete the 'old' folder if it exists (will be in the patcher folder)

> GUPE8P.iso: The system cannot find the file specified. The system cannot find the file specified

Make sure your ISO is in the folder and named GUPE8P.iso.
If on Windows you might have extensions turned off so you may have accidentally named it GUPE8P.iso.iso

Alternatively use something like https://kotcrab.github.io/xdelta-wasm/
and point to the VCDIFF file instead of using the patcher included.

**Comment by explosionenjoyer** [comment]
ah, that makes sense, thx
