### ISSUE TITLE
Save Data not loading.

### ISSUE THREAD

**Issue by GokaiSanyu** [ShadowTheHedgehogHacking/ShdTH-Reloaded#6]
Running on Dolphin and it while it generates a GCI file when prompted the first time, the file reads as "8P-__00__UPE-SHADOWTHEHEDGEHOG.gci" and can't be detected by the game on subsequent save attempts. When prompted to make a new save and hitting "Yes," this menu basically loops unless you tell it not to make a save at all.

It also has Memory Card errors with an already present vanilla Shadow the Hedgehog save.

**Comment by dreamsyntax** [comment]
This happens if you enable "Reduce Bloom" Gecko Code without having read the description / edited the code. Either disable the code or edit the XXXXXXXX to the value you desire.

Reduced Bloom is already built in to the ISO patch, so the code is only if you dislike our change and want to customize it yourself.

This is a common error at this point, so we will definitely change that in 1.0.1 to just assume Reloaded's value for that code (even though it would change nothing).

Pinning this, since it is likely to be encountered by others.
